language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to run tests

install:
  pip install lxml pytest nose

script:  
  py.test

notifications:
  email:
    recipients:
      - charlie.clark@clark-consulting.eu
