language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to run tests

install:
  pip install lxml
  pip install pytest
  pip install nose

script:  pytest

notifications:
  email:
    recipients:
      - charlie.clark@clark-consulting.eu
