image: openpyxl/openpyxl-ci

pipelines:
  default:
    - step:
      script:
        - /tools/clean-launch.sh tox --skip-missing-interpreters -- -qrf
        - curl -sSL https://download.sourceclear.com/ci.sh | sh
