image: openpyxl/openpyxl-ci

pipelines:
  default:
  - step:
      caches:
        - pip
      script:
        - /tools/clean-launch.sh tox --skip-missing-interpreters -- -qrf
        - /tools/clean-launch.sh tox -e cov
