image: openpyxl/openpyxl-ci

pipelines:
  default:
    - step:
        script:
          - /tools/clean-launch.sh tox --skip-missing-interpreters
          - /tools/clean-launch.sh /tools/build-coverage.sh
