image: jjuanda/numpy-pandas

pipelines:
  default:
    - step:
        script:
          - pip install -U -r requirements.txt
          - pip --version
          - tox --version
          - tox -- -xrf openpyxl
