#Autogenerated schema
from openpyxl2.descriptors.serialisable import Serialisable
from openpyxl2.descriptors import (
    Typed,)

# same as related

class SheetBackgroundPicture(Serialisable):

    tagname = "sheetBackgroundPicture"



    pass
